environmentName: CarRacing-v3
runName: RecLat
seed: 1

# total gradients steps will be iterations * replayRatio
iterationsNum: 100
replayRatio: 100
saveMetrics: True        # Saves metrics at replayRatio interval
saveCheckpoints: True
checkpointInterval: 1000
resume: False
checkpointToLoad: 2k

episodesBeforeStart: 2
numInteractionEpisodes: 1
numEvaluationEpisodes: 1

dreamer:
    batchSize: 32
    batchLength: 64
    imaginationHorizon: 15

    freeNats: 3
    discount: 0.99
    lambda_: 0.95

    useContinuationPrediction: False
    actorLR: 0.00004
    criticLR: 0.0001
    worldModelLR: 0.0002
    gradientNormType: 2
    gradientClip: 100

    recurrentSize: 600
    latentSize: 600 # Exchange for length and size
    encodedObsSize: 1024 #FIXME: You can't just modify it

    buffer:
        capacity: 50000

    encoder: 
        depth: 32
        stride: 2
        kernel_size: 4
        activation: ReLU

    decoder: 
        depth: 32
        stride: 2
        kernel_size: 5
        activation: ReLU

    recurrentModel: 
        hiddenSize: 200
        activation: ELU

    priorNet: 
        hiddenSize: 200
        numLayers: 2
        activation: ELU
        min_std: 0.1

    posteriorNet:
        hiddenSize: 200
        numLayers: 2
        activation: ELU
        min_std: 0.1
        
    reward:
        hiddenSize: 400
        numLayers: 2
        activation: ELU

    continuation:
        hiddenSize: 400
        numLayers: 3
        activation: ELU
    
    actor:
        hiddenSize: 400
        min_std: 0.0001
        init_std: 5.
        mean_scale: 5
        activation: ELU
        numLayers: 2

    critic: 
        hiddenSize: 400
        activation: ELU
        numLayers: 3 

folderNames:
    metricsFolder: metrics
    plotsFolder: plots
    checkpointsFolder: checkpoints
    videosFolder: videos
